### PR TITLE
Create AllocateBooks.cpp

### PR DESCRIPTION
**Pull request by Amisha328**
Add a Binary Search Program in C++ to perform the Allocate Books program.

Please review and accept the PR for issue #71.

Thank you !! :)

### CODE REVIEW

**Comment by Amisha328** [comment]
Hi @MSubhajitIND,

Is this repository not part of hacktoberfest23, because it shows excluded?

image

**Comment by MSubhajitIND** [comment]
> hacktoberfest23, because it shows excluded?

If I say from myside.....I got accepted 2 pull requests from this repo In Hactober 2023. 


But still need to confirmation from admin as this year new rules applied in Hacktoberfest. @random957654  Is this repo Excluded? Please Check.

**Comment by MSubhajitIND** [comment]
> Hi @MSubhajitIND,
> 
> Is this repository not part of hacktoberfest23, because it shows excluded?
> 
> image

If admin confirm this is excluded from Hacktober, then all have to contribute opensource projects like Appwrite ,FreeCodeCamp like open source repo which will hard for Beginners.

**Comment by MSubhajitIND** [comment]
Till Confirmation ...You will find opensource Official Repos From This link provided by hacktoberfest authorities.
https://hacktoberfest-projects.vercel.app/

Thanks,

**Comment by Amisha328** [comment]
> Till Confirmation ...You will find opensource Official Repos From This link provided by hacktoberfest authorities. https://hacktoberfest-projects.vercel.app/
> 
> Thanks, @Amisha328

Sure, thanks a lot !! :)

**Pull request merged**
